In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd

data = {'Weather': ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 
                    'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'],
    
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 
                    'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'],
        
       'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 
                'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)
le_weather = LabelEncoder()
le_temperature = LabelEncoder()
le_play = LabelEncoder()

df['Weather'] = le_weather.fit_transform(df['Weather'])
df['Temperature'] = le_temperature.fit_transform(df['Temperature'])
df['Play'] = le_play.fit_transform(df['Play'])

X = df[['Weather', 'Temperature']].values
y = df['Play'].values

knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X, y)

input_data = np.array([[le_weather.transform(['Overcast'])[0], 
                        le_temperature.transform(['Mild'])[0]]])
prediction = knn.predict(input_data)

play_decision = le_play.inverse_transform(prediction)
print("Prediction (Play or Not):", play_decision[0])


Prediction (Play or Not): Yes


In [13]:
import math

query_instance = (3, 7)
samples = [
    {"point": (7, 7), "classification": "Bad"},
    {"point": (7, 4), "classification": "Bad"},
    {"point": (3, 4), "classification": "Good"},
    {"point": (1, 4), "classification": "Good"}
]

def euclidean_distance(point1, point2):
    return math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)

distances = []
for sample in samples:
    distance = euclidean_distance(query_instance, sample["point"])
    distances.append({"distance": distance, "classification": sample["classification"]})

distances.sort(key=lambda x: x["distance"])
print("Distances from query instance to each sample:")
for d in distances:
    print(f"Distance: {d['distance']:.2f}, Classification: {d['classification']}")

predicted_classification = distances[0]["classification"]
print(f"\nPredicted Classification: {predicted_classification}")


Distances from query instance to each sample:
Distance: 3.00, Classification: Good
Distance: 3.61, Classification: Good
Distance: 4.00, Classification: Bad
Distance: 5.00, Classification: Bad

Predicted Classification: Good


In [14]:
import math
from collections import Counter

query_instance = (3, 7)
samples = [
    {"point": (7, 7), "classification": "Bad"},
    {"point": (7, 4), "classification": "Bad"},
    {"point": (3, 4), "classification": "Good"},
    {"point": (1, 4), "classification": "Good"}
]

def euclidean_distance(point1, point2):
    return math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)

distances = []
for sample in samples:
    distance = euclidean_distance(query_instance, sample["point"])
    distances.append({"distance": distance, "classification": sample["classification"]})

K = 3
distances.sort(key=lambda x: x["distance"])
nearest_neighbors = distances[:K]

print("Distances from query instance to the 3 nearest neighbors:")
for d in nearest_neighbors:
    print(f"Distance: {d['distance']:.2f}, Classification: {d['classification']}")

classifications = [neighbor["classification"] for neighbor in nearest_neighbors]

predicted_classification = Counter(classifications).most_common(1)[0][0]
print(f"\nPredicted Classification (K=3): {predicted_classification}")


Distances from query instance to the 3 nearest neighbors:
Distance: 3.00, Classification: Good
Distance: 3.61, Classification: Good
Distance: 4.00, Classification: Bad

Predicted Classification (K=3): Good


In [61]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from scipy.spatial.distance import pdist, squareform
import numpy as np
import pandas as pd

df = pd.read_csv('gender_classification.csv')

le_long_hair = LabelEncoder()
le_forehead_width_cm = LabelEncoder()
le_forehead_height_cm = LabelEncoder()
le_nose_wide= LabelEncoder()
le_nose_long = LabelEncoder()
le_lips_thin = LabelEncoder()
le_distance_nose_to_lip_long = LabelEncoder()
le_gender = LabelEncoder()

df['long_hair'] = le_long_hair.fit_transform(df['long_hair'])
df['forehead_width_cm'] = le_forehead_width_cm.fit_transform(df['forehead_width_cm'])
df['le_forehead_height_cm'] = le_forehead_height_cm.fit_transform(df['forehead_height_cm'])
df['nose_wide'] = le_nose_wide.fit_transform(df['nose_wide'])
df['nose_long'] = le_nose_long.fit_transform(df['nose_long'])
df['lips_thin'] = le_lips_thin.fit_transform(df['lips_thin'])
df['distance_nose_to_lip_long'] = le_distance_nose_to_lip_long.fit_transform(df['distance_nose_to_lip_long'])
df['gender'] = le_gender.fit_transform(df['gender'])

X = df[['long_hair','forehead_width_cm' ,'forehead_height_cm','nose_wide','nose_long','lips_thin','distance_nose_to_lip_long']].values 
y = df['gender'].values  

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

input_data = np.array([[le_long_hair.transform(['1'])[0],
                        le_forehead_width_cm.transform(['13'])[0],
                        le_forehead_height_cm.transform(['5.9'])[0],
                        le_nose_wide.transform(['1'])[0],
                        le_nose_long.transform(['0'])[0],
                        le_lips_thin.transform(['1'])[0],
                        le_distance_nose_to_lip_long.transform(['1'])[0]]])

prediction = knn.predict(input_data)

predicted_class = le_gender.inverse_transform(prediction)
print("Prediction:", predicted_class[0])

first_5_rows = X[:5]
pairwise_distances_first_5 = squareform(pdist(first_5_rows, metric='euclidean'))
print("Pairwise Euclidean Distances for the first 5 rows: \n", pairwise_distances_first_5)



Accuracy: 0.957042957042957
Prediction: Male
Pairwise Euclidean Distances for the first 5 rows: 
 [[ 0.         22.07917571  1.42828569 26.05762844 17.08917786]
 [22.07917571  0.         22.08642117  4.3         5.22015325]
 [ 1.42828569 22.08642117  0.         26.01999231 17.15109326]
 [26.05762844  4.3        26.01999231  0.          9.22171351]
 [17.08917786  5.22015325 17.15109326  9.22171351  0.        ]]
